### ISSUE TITLE
MinIntervalBetweenBackups valid range

### ISSUE THREAD

**Issue by Aireil** [NightmareXIV/JustBackup#22]
Hey, love the new feature to limit backups, it was the main thing that made it impossible to use the plugin (as my game restarts every 3s 👁️). However, I was wondering why the limit on the time. I wanted to set it to 1440 minutes to have a backup every 24h, but 360 is the max :(.
Thanks for the update, that setting is good either way!

**Comment by Limiana** [comment]
hey, just needed some value to limit it so people don't set it to once a month or so, 360 was what I thought of at first, I'll up it to 24 hours in next update, maybe a bit more even

**Comment by Aireil** [comment]
Ah I see, thank you!
